# Generated by Django 4.2.14 on 2024-09-30 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_yalidine_wilaya'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('order_items', models.ManyToManyField(to='app.orderitem')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.wilaya')),
            ],
        ),
    ]
