# Generated by Django 4.2.14 on 2024-10-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order_adress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Township',
            new_name='Maktab',
        ),
        migrations.AddField(
            model_name='wilaya',
            name='domicile_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wilaya',
            name='maktab',
            field=models.ManyToManyField(to='app.maktab'),
        ),
        migrations.AddField(
            model_name='wilaya',
            name='yalidine_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Yalidine', 'yalidine'), ('Domicile', 'domicile')], default=('Yalidine', 'yalidine'), max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='wilaya',
            field=models.ForeignKey(default='Alger', on_delete=django.db.models.deletion.PROTECT, to='app.wilaya'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='name',
            field=models.CharField(default='Alger', max_length=100),
        ),
        migrations.DeleteModel(
            name='Yalidine',
        ),
    ]
