# Generated by Django 4.2.14 on 2024-10-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_township_maktab_wilaya_domicile_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='desktop',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='township',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='wilaya',
            field=models.CharField(max_length=40),
        ),
    ]
