# Generated by Django 4.2.14 on 2024-10-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_order_desktop_order_township_alter_order_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(null=True, to='app.orderitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
