# Generated by Django 4.2.14 on 2024-10-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_product_description_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('OUT OF STOCK', 'out of stock')], max_length=15, unique=True),
        ),
    ]
